# Generated by Django 5.1.4 on 2024-12-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('catalog', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='+', to='catalog.order'),
        ),
    ]
