# Generated by Django 5.1.4 on 2024-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(null=True)),
                ('ordered_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('registration', 'Оформление заказа'), ('dedlivery', 'Доставка заказа'), ('done', 'Заказ выполнен')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('electric', 'Электрогитара'), ('acoustic', 'Акустическая гитара'), ('classical', 'Классическая гитара')], max_length=64)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
